name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip build-essential git
        pip install buildozer cython

    - name: Set up Android SDK
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip
        mkdir -p $HOME/android-sdk/cmdline-tools
        unzip -q commandlinetools-linux-8092744_latest.zip -d $HOME/android-sdk/cmdline-tools
        yes | $HOME/android-sdk/cmdline-tools/cmdline-tools/bin/sdkmanager --licenses
        $HOME/android-sdk/cmdline-tools/cmdline-tools/bin/sdkmanager "platform-tools" "build-tools;35.0.0" "platforms;android-31"

    - name: Build APK
      run: |
        cd ${{ github.workspace }}
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: myapp-apk
        path: bin/*.apk
