name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git wget unzip
          pip install --upgrade pip
          pip install buildozer cython

      - name: Set up Android SDK
        run: |
          # Create necessary directories
          mkdir -p cmdline-tools
          
          # Download Android command line tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O sdk-tools.zip
          if [ $? -ne 0 ]; then
            echo "Error: Failed to download Android SDK command line tools."
            exit 1
          fi

          # Unzip the command line tools
          unzip sdk-tools.zip -d cmdline-tools
          if [ $? -ne 0 ]; then
            echo "Error: Failed to unzip Android SDK command line tools."
            exit 1
          fi

          # Move to the correct folder structure
          mkdir -p cmdline-tools/latest
          mv cmdline-tools/cmdline-tools/* cmdline-tools/latest/
          
          # Set up environment variables for Android SDK
          mkdir -p $HOME/android-sdk
          mv cmdline-tools $HOME/android-sdk/cmdline-tools
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin

          # Accept licenses and install necessary build tools
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "build-tools;35.0.0"
          if [ $? -ne 0 ]; then
            echo "Error: Failed to install Android SDK build tools."
            exit 1
          fi

      - name: Build APK
        run: |
          cd ${{ github.workspace }}
          buildozer -v android debug
          if [ $? -ne 0 ]; then
            echo "Error: Buildozer failed to build the APK."
            exit 1
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: MyApp-APK
          path: bin/*.apk
